/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as SeasonEventIndexImport } from './routes/$season/$event/index'
import { Route as SeasonEventQueuerIndexImport } from './routes/$season/$event/queuer/index'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SeasonEventIndexRoute = SeasonEventIndexImport.update({
  id: '/$season/$event/',
  path: '/$season/$event/',
  getParentRoute: () => rootRoute,
} as any)

const SeasonEventQueuerIndexRoute = SeasonEventQueuerIndexImport.update({
  id: '/$season/$event/queuer/',
  path: '/$season/$event/queuer/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/$season/$event/': {
      id: '/$season/$event/'
      path: '/$season/$event'
      fullPath: '/$season/$event'
      preLoaderRoute: typeof SeasonEventIndexImport
      parentRoute: typeof rootRoute
    }
    '/$season/$event/queuer/': {
      id: '/$season/$event/queuer/'
      path: '/$season/$event/queuer'
      fullPath: '/$season/$event/queuer'
      preLoaderRoute: typeof SeasonEventQueuerIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$season/$event': typeof SeasonEventIndexRoute
  '/$season/$event/queuer': typeof SeasonEventQueuerIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$season/$event': typeof SeasonEventIndexRoute
  '/$season/$event/queuer': typeof SeasonEventQueuerIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$season/$event/': typeof SeasonEventIndexRoute
  '/$season/$event/queuer/': typeof SeasonEventQueuerIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/$season/$event' | '/$season/$event/queuer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/$season/$event' | '/$season/$event/queuer'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/$season/$event/'
    | '/$season/$event/queuer/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SeasonEventIndexRoute: typeof SeasonEventIndexRoute
  SeasonEventQueuerIndexRoute: typeof SeasonEventQueuerIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SeasonEventIndexRoute: SeasonEventIndexRoute,
  SeasonEventQueuerIndexRoute: SeasonEventQueuerIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/$season/$event/",
        "/$season/$event/queuer/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/$season/$event/": {
      "filePath": "$season/$event/index.tsx"
    },
    "/$season/$event/queuer/": {
      "filePath": "$season/$event/queuer/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
