/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeasonEventIndexRouteImport } from './routes/$season/$event/index'
import { Route as SeasonEventQueuerIndexRouteImport } from './routes/$season/$event/queuer/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonEventIndexRoute = SeasonEventIndexRouteImport.update({
  id: '/$season/$event/',
  path: '/$season/$event/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonEventQueuerIndexRoute = SeasonEventQueuerIndexRouteImport.update({
  id: '/$season/$event/queuer/',
  path: '/$season/$event/queuer/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$season/$event': typeof SeasonEventIndexRoute
  '/$season/$event/queuer': typeof SeasonEventQueuerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$season/$event': typeof SeasonEventIndexRoute
  '/$season/$event/queuer': typeof SeasonEventQueuerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$season/$event/': typeof SeasonEventIndexRoute
  '/$season/$event/queuer/': typeof SeasonEventQueuerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/$season/$event' | '/$season/$event/queuer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/$season/$event' | '/$season/$event/queuer'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/$season/$event/'
    | '/$season/$event/queuer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SeasonEventIndexRoute: typeof SeasonEventIndexRoute
  SeasonEventQueuerIndexRoute: typeof SeasonEventQueuerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$season/$event/': {
      id: '/$season/$event/'
      path: '/$season/$event'
      fullPath: '/$season/$event'
      preLoaderRoute: typeof SeasonEventIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$season/$event/queuer/': {
      id: '/$season/$event/queuer/'
      path: '/$season/$event/queuer'
      fullPath: '/$season/$event/queuer'
      preLoaderRoute: typeof SeasonEventQueuerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SeasonEventIndexRoute: SeasonEventIndexRoute,
  SeasonEventQueuerIndexRoute: SeasonEventQueuerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
